# The name of the workflow.
name: ContinuousIntegration

# Controls when the action will run. Triggers the workflow on push or pull request events.
on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build".
  build:
    # The type of runner that the job will run on.
    runs-on: windows-latest
    name: ContinuousIntegration

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
    - uses: actions/checkout@v5.0.0

    # MSBuild is used for building applications via the commandline.  
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2.0.0
    
    - name: Restore NuGet packages
      run: nuget restore LearnGitHub.sln
      
    - name: Build the Solution
      run: msbuild LearnGitHub.sln
